name: Linux Build

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y clang g++ cmake

      - name: Configure CMake
        run: |
          cmake -B build \
            -DCMAKE_BUILD_TYPE=Dev_Release \
            -S ${{ github.workspace }}

      - name: Build
        run: cmake --build build --config Release

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: vmaware-linux-x86_64
          path: build/vmaware
          if-no-files-found: error
          retention-days: 30
